### ISSUE TITLE
Botón sin ninguna acción

### ISSUE THREAD

**Issue by DanielOchoaSuarez** [abenitezm20/Equipo_LAAD_ViniloMovil#34]
**Comportamiento Esperado**
En esta primera versión de la aplicación, al listar álbumes solo se debe imprimir el catalogo de ellos.

**Comportamiento Actual**
La lista de álbumes presenta un botón flotante que no genera ninguna acción

**Pasos a reproducir**
Ingresar a la aplicación y dar clic en el botón Coleccionista o Visitante

**Evidencias**
https://user-images.githubusercontent.com/111323164/235376346-9aa6b7d1-8cdc-4878-b8c7-6e1c049eb981.mp4

**Ambiente de ejecución**
App Versión: 1.0.0
OS: Dispositivo virtual Pixel 4 - Android 5.0 API 21

**Comment by abenitezm20** [comment]
Se realizo la correccion en el codigo, en las siguientes entregas se utilizara este boton flotante.
