### ISSUE TITLE
Fecha artista sin formato

### ISSUE THREAD

**Issue by DanielOchoaSuarez** [abenitezm20/Equipo_LAAD_ViniloMovil#35]
**Comportamiento Esperado**
Al listar artistas se debe imprimir las fechas con el formato yyyy-MM-dd

**Comportamiento Actual**
La lista de artistas imprime las fechas de nacimiento sin formato

**Pasos a reproducir**
1. Ingresar a la aplicación y dar clic en el botón Coleccionista o Visitante
2. Desplegar el menú
3. Ingresar a la opción Artistas

**Evidencias**
https://user-images.githubusercontent.com/111323164/235376842-a781e0a6-0975-4338-b47a-721dd67e60e0.mp4

**Ambiente de ejecución**
App Versión: 1.0.0
OS: Dispositivo virtual Pixel 4 - Android 5.0 API 21

**Comment by alex-archdev** [comment]
Se realiza el ajuste indicado, ahora la lista de artistas tiene la fecha con el formato correcto
